# Site settings
title: Yuping Ke
email: jameskes02@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# 社交媒体账号（修正变量名和内容）
linkedin_username: yuping-ke-000b60323  # 仅保留 LinkedIn 路径部分
phone_number: "+447541041989"          # 新增手机号变量，移除多余符号

# 原有账号（若需要保留）
# twitter_username: your-twitter-handle  # 若不用可注释掉
# github_username: your-github-id       # 若不用可注释掉

# Build settings
markdown: kramdown
